[book]
title = "雑本"
authors = ["hayashi3017"]
language = "ja"
multilingual = false
src = "src"

[build]
build-dir = "book"
create-missing = false
use-default-preprocessors = true
extra-watch-dirs = ["facts", "templates", "generated"]

[output.html]
theme = "theme"
default-theme = "ayu"
git-repository-url = "https://github.com/hayashi3017/zatsu-book"
edit-url-template = "https://github.com/hayashi3017/zatsu-book/edit/main/{path}"
site-url = "/zatsu-book/"
additional-js = ["theme/searcher.js"]

[output.html.fold]
enable = true
level = 1

[output.markdown]

[preprocessor.links]

[preprocessor.index]
