[book]
title = "へえー図鑑"
authors = ["hayashi3017"]
language = "ja"
multilingual = false
src = "src"

[build]
build-dir = "book"
create-missing = false
use-default-preprocessors = true
extra-watch-dirs = ["facts", "templates", "generated"]

[output.html]
default-theme = "ayu"
git-repository-url = "https://github.com/hayashi3017/zatsu-book"
edit-url-template = "https://github.com/hayashi3017/zatsu-book/edit/main/{path}"
site-url = "/zatsu-book/"

[output.markdown]

[preprocessor.links]

[preprocessor.index]
