genres:
  food:
    label: 食べ物
  japan:
    label: 日本
  local:
    label: ご当地
  mascots:
    label: マスコット
  money:
    label: お金
  science:
    label: 科学
tags:
  coin-design:
    label: デザイン
  currency:
    label: 貨幣
  official-source:
    label: 公式ソース
